#!/usr/bin/env bash
set -euo pipefail

# ─── Config ──────────────────────────────────────────────────────────────────
CONTRACT="EcoReceiptNFT"
CHAIN_ID="${CHAIN_ID:-10143}"
NETWORK_NAME="${NETWORK_NAME:-monad-testnet}"
ARTIFACT="out/${CONTRACT}.sol/${CONTRACT}.json"
BROADCAST_FILE="broadcast/Deploy${CONTRACT}.s.sol/${CHAIN_ID}/run-latest.json"
OUT_DIR="${OUT_DIR:-./frontend}"

# ─── Build ───────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║          Building contracts...               ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
forge build --silent

# ─── Validate artifacts ──────────────────────────────────────────────────────
if [ ! -f "${ARTIFACT}" ]; then
  echo "❌  Artifact not found: ${ARTIFACT}"
  echo "    Run 'forge build' first."
  exit 1
fi

if [ ! -f "${BROADCAST_FILE}" ]; then
  echo "❌  Broadcast file not found: ${BROADCAST_FILE}"
  echo "    Run deploy.sh (or forge script ... --broadcast) first."
  exit 1
fi

# ─── Extract data ────────────────────────────────────────────────────────────
ABI=$(jq '.abi' "${ARTIFACT}")

CONTRACT_ADDRESS=$(jq -r '
  .transactions[]
  | select(.contractName == "'"${CONTRACT}"'" and .transactionType == "CREATE")
  | .contractAddress
' "${BROADCAST_FILE}")

DEPLOY_TX=$(jq -r '
  .transactions[]
  | select(.contractName == "'"${CONTRACT}"'" and .transactionType == "CREATE")
  | .hash
' "${BROADCAST_FILE}")

DEPLOY_BLOCK=$(jq -r '
  .receipts[0].blockNumber // "unknown"
' "${BROADCAST_FILE}" | xargs printf "%d" 2>/dev/null || echo "unknown")

DEPLOY_TIMESTAMP=$(jq -r '.timestamp' "${BROADCAST_FILE}")

if [ -z "${CONTRACT_ADDRESS}" ] || [ "${CONTRACT_ADDRESS}" = "null" ]; then
  echo "❌  Could not parse contract address from broadcast."
  exit 1
fi

# ─── Write output ────────────────────────────────────────────────────────────
mkdir -p "${OUT_DIR}"

# ── 1. Canonical JSON (abi + deployment metadata) ────────────────────────────
jq -n \
  --argjson abi "${ABI}" \
  --arg address "${CONTRACT_ADDRESS}" \
  --arg chainId "${CHAIN_ID}" \
  --arg network "${NETWORK_NAME}" \
  --arg deployTx "${DEPLOY_TX}" \
  --arg deployBlock "${DEPLOY_BLOCK}" \
  --arg deployTimestamp "${DEPLOY_TIMESTAMP}" \
  '{
    contractName: "'"${CONTRACT}"'",
    address: $address,
    chainId: ($chainId | tonumber),
    network: $network,
    deployTx: $deployTx,
    deployBlock: ($deployBlock | if . == "unknown" then . else tonumber end),
    deployTimestamp: ($deployTimestamp | tonumber),
    abi: $abi
  }' > "${OUT_DIR}/${CONTRACT}.json"

echo "📄  ${OUT_DIR}/${CONTRACT}.json"

# ── 2. TypeScript constants ───────────────────────────────────────────────────
ABI_TS=$(jq -c '.abi' "${ARTIFACT}")

cat > "${OUT_DIR}/${CONTRACT}.ts" <<TSEOF
// Auto-generated by export-abi.sh — do not edit manually.
// Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

export const ${CONTRACT}_ADDRESS = "${CONTRACT_ADDRESS}" as const;

export const ${CONTRACT}_CHAIN_ID = ${CHAIN_ID} as const;

export const ${CONTRACT}_NETWORK = "${NETWORK_NAME}" as const;

export const ${CONTRACT}_ABI = ${ABI_TS} as const;

export type ${CONTRACT}ABI = typeof ${CONTRACT}_ABI;
TSEOF

echo "📄  ${OUT_DIR}/${CONTRACT}.ts"

# ── 3. Minimal ABI-only JSON (for lightweight imports) ───────────────────────
jq '.abi' "${ARTIFACT}" > "${OUT_DIR}/${CONTRACT}.abi.json"
echo "📄  ${OUT_DIR}/${CONTRACT}.abi.json"

# ─── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║             Export complete ✅               ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "  Contract  : ${CONTRACT}"
echo "  Address   : ${CONTRACT_ADDRESS}"
echo "  Chain ID  : ${CHAIN_ID} (${NETWORK_NAME})"
echo "  Deploy TX : ${DEPLOY_TX}"
echo "  Output    : ${OUT_DIR}/"
echo ""
echo "  Files:"
echo "    ${CONTRACT}.json      ← full metadata + ABI"
echo "    ${CONTRACT}.ts        ← TypeScript constants"
echo "    ${CONTRACT}.abi.json  ← ABI only"
echo ""
